
# auto-generated by configure
PREFIX = /usr/local
VERSION = 2.8.0
CC = gcc
CFLAGS = -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -mmacosx-version-min=10.6 -I/usr/local/Cellar/libpng/1.6.26/include/libpng16 
LDFLAGS =  -mmacosx-version-min=10.6 -L/usr/local/Cellar/libpng/1.6.26/lib -lpng16 -lz -lm
COCOA_READER = 0
SOLIBSUFFIX = dylib

